POST  {{host}}/Authentication/Register
Content-Type: application/json
Accept: application/json

{
"firstName": "Reza",
"lastName": "shirazi",
"email": "shirazi.reza@hotmail.com",
"password": "Welcome123#"
}